### ISSUE TITLE
Fix or Remove "Preview" option for users editing CNX content

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/Products.RhaptosModuleEditor#23]
# Scenario
When a user is creating content in legacy CNX they are given the option to preview their resource to see what it will look like before they publish it.  This routinely breaks, yielding a 404 error.

According to the content managers:
"...the preview button isn’t reliable"
"... it isn’t a guarantee of how it’ll show up in CNX or the PDF"
"we don’t use it cause it’s essentially useless"

The preview option needs to be fixed to enable its use or needs to hidden/removed so that users don't struggle with a broken feature.

# Steps to Reproduce

* **Product**: [ ] Tutor   [ ] Concept Coach [ ] OS Web [ ] Content Production Toolkit [X] CNX

* **How many times were you able to reproduce the issue?** 
95% of the time?

* **Images or Screenshots Included:** [ ] Yes  [X] No  (_attach below_)

# Environment:

* **Instance**: [X] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [X] Mac OSX  [X] Windows  [ ] iOS  [ ] Android
* **Browser**: [X] Chrome  [X] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact

* **Severity**: [ ] High [X] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [X] Medium  [ ] Low

# Acceptance Criteria
- [ ] this issue has been moved into the Connexions org with the following metadata:
Milestone: CNX Q4
Estimate: 2 (or another # if different)
Releases: TBD

**Comment by edwoodward** [comment]
https://github.com/Connexions/Products.RhaptosModuleEditor/pull/24

**Comment by brittweinstein** [comment]
Test plan: Log into legacy and try to edit somthing. You should not see "print preview"

**Comment by omehes** [comment]
As per discussion with Ed and verifying on staging.cnx.org, the Preview links:
- are removed from Preview tab
- not yet removed from Publish tab
- not yet removed from Module Status bar

Fix is coming.

**Comment by openstaxalina** [comment]
Changes just discussed with @edwoodward and @reedstrm. cc @omehes - we will try to get all of these changes into the next rev on staging.

![removingpreview](https://user-images.githubusercontent.com/7863733/47747609-bc584600-dc56-11e8-8b42-a9c67a421bfa.png)

**Comment by omehes** [comment]
Verified on the latest build from 31/10/2018 on staging.cnx.org
All references to preview (online, print) are removed apart from the Preview tab, which is still present and when clicked, it opens an error page. See attached:

<img width="1279" alt="screen shot 2018-10-31 at 5 45 16 pm" src="https://user-images.githubusercontent.com/44207656/47859469-6bfaf880-ddbc-11e8-91b3-99319d962ab1.png">

**Comment by omehes** [comment]
Reverified after scrum meeting. All references to preview (online, print, preview tab) were removed.
legacy-staging.cnx.org
FIXED
@edwoodward @brittweinstein
